### ISSUE TITLE
Question: Obtaining Advanced Chest Async

### ISSUE THREAD

**Issue by tastybento** [DeadSilenceIV/AdvancedChestsAPI#1]
Hi - I write BentoBox (BSkyBlock, etc.) and I have a Level addon that a user has asked to be compatible with AdvancedChests. The Level addon essentially counts every block in the island space and scans chests to create a score for the island. As this can take a while, I do it all async by grabbing chunk snapshots and try to avoid getting any blocks on the main thread.

In your API, I see a way to obtain an AdvancedChest via a Location:

`public AdvancedChest getNonLoadedChest(Location location)`

https://github.com/DeadSilenceIV/AdvancedChestsAPI/blob/04aeea0a51765fb65789259e989109750ae08e34/src/main/java/us/lynuxcraft/deadsilenceiv/advancedchests/managers/ChestsManager.java#L20

Would it be safe to use this for all chests? Could it run in an async thread?

**Comment by DeadSilenceIV** [comment]
Hello tastybento, i'm glad you want to add support for AdvancedChests.

1. The method `public AdvancedChest getNonLoadedChest(Location location)` is used for getting an advancedchests that couldn't be loaded by externals factors (hard config changes), if you want to get a loaded advancedchest you have to use the method `public AdvancedChest getAdvancedChest(Block block)`, however i'll probably change it very soon to receive a location instead of a block.
2. Loaded AdvancedChests are stored in CopyOnWriteArrayList however no-loaded AdvancedChests aren't, however i will change this tomorrow to allow you to do run these methods in an async thread.

**Comment by tastybento** [comment]
Excellent. Yes, having to step out of async to get a `Block` is the main issue, especially if it's not actually required to get the contents of the chest. So if you can add an API to enable that, then that would be excellent.

**Comment by DeadSilenceIV** [comment]
You should be able to do what you need. with the method i added.

https://github.com/DeadSilenceIV/AdvancedChestsAPI/blob/d9566dec47f10f6b25f91a170cc3188487c59d27/src/main/java/us/lynuxcraft/deadsilenceiv/advancedchests/managers/ChestsManager.java#L62
